name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      # TODO: this should only apply for PRs and not on the `main` branch
      RUSTFLAGS: -Dwarnings

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain:  nightly
        profile:    minimal
        components: clippy
        override:   true

    - name: Build
      run: cargo build --verbose

    - name: Lint
      run: cargo clippy --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Generate docs
      run: cargo doc --verbose --no-deps
