name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain:  nightly
        profile:    minimal
        components: clippy, miri
        override:   true

    - name: Install cargo-nextest
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-nextest

    - name: Build
      run: cargo build --verbose --all-targets

    - name: Lint
      run: cargo clippy --verbose --all-targets

    - name: Run tests
      run: cargo nextest run --verbose

    - name: Run tests under Miri
      run: cargo miri nextest run --verbose

    - name: Generate docs
      run: cargo doc --verbose --no-deps
